channels:
  - bioconda
  - conda-forge
dependencies:
  - python =3.11
  - snakemake-minimal >=7.3
  - jinja2
  - matplotlib
  - graphviz
  - bcftools =1.15
  - samtools =1.15
  - bwa =0.7.17
  - pysam =0.22.1
  - pygments
